import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F7FA',
  },
  header: {
    paddingHorizontal: 20,
    paddingVertical: 20,
    backgroundColor: '#2E5B9A',
    alignItems: 'center',
    elevation: 4,
  },
  headerText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  mainCard: {
    width: '94%',
    alignSelf: 'center',
    borderRadius: 30,
    padding: 30,
    marginTop: 20,
    alignItems: 'center',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  gaugeContainer: {
    width: 180,
    height: 180,
    borderRadius: 90,
    borderWidth: 8,
    borderColor: 'rgba(255,255,255,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  valueText: {
    fontSize: 52,
    fontWeight: 'bold',
    color: 'white',
  },
  unitText: {
    fontSize: 18,
    color: 'white',
    fontWeight: '600',
  },
  statusBadge: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 25,
    marginTop: 25,
    alignItems: 'center',
    elevation: 2,
  },
  statusText: {
    fontWeight: 'bold',
    marginLeft: 8,
    fontSize: 14,
  },
  // ESTILO DO NOVO CARD DE CONEXÃO
  connectionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    width: '90%',
    alignSelf: 'center',
    marginTop: 20,
    padding: 15,
    borderRadius: 20,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  connectionDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: 15,
  },
  connectionLabel: {
    fontSize: 10,
    color: '#999',
    fontWeight: 'bold',
  },
  connectionStatus: {
    fontSize: 15,
    fontWeight: 'bold',
  },
  instructionCard: {
    width: '90%',
    padding: 20,
    borderRadius: 20,
    marginTop: 20,
    borderWidth: 2,
    alignItems: 'center',
    alignSelf: 'center',
  },
  instructionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 8,
    textAlign: 'center',
  },
  instructionText: {
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 22,
  },
  settingsContainer: {
    padding: 20,
    width: '100%',
  },
  settingItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'white',
    padding: 18,
    borderRadius: 15,
    marginBottom: 12,
    elevation: 2,
  },
  settingLabel: {
    fontSize: 16,
    color: '#333',
    marginLeft: 12,
    flex: 1,
    fontWeight: '500',
  },
  logoutItem: {
    marginTop: 30,
    borderWidth: 0, 
  },
  logoutText: {
    color: '#C62828',
    fontWeight: 'bold',
    fontSize: 16,
  },
  bottomTab: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: 'white',
    paddingVertical: 12,
    position: 'absolute',
    bottom: 0,
    width: '100%',
    borderTopWidth: 1,
    borderTopColor: '#EEE',
    elevation: 10,
  },
  tabItem: {
    alignItems: 'center',
    flex: 1,
  },
  tabText: {
    fontSize: 12,
    color: '#999',
    marginTop: 4,
    fontWeight: '500',
  },
});